name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *" # 每天UTC时间18:00触发
  workflow_dispatch: # 允许手动触发
  # run on every push on the master branch
  push:
    branches:
    - main #每次有push这个分支的时候都触发

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  #自己创建的 Personal Access Token (PAT)并添加到GitHub Secrets
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push output HEAD:output
          fi